Restore neg_equiv_lemma
hacspec/hax pull request #1004
Opened 2024-10-16 08:22 UTC by mamonet

This PR restores `neg_equiv_lemma` which is needed for portable compress proofs.

2024-10-16 08:29 UTC, W95Psp requested changes
LGTM, but shouldn't this lemma be two lemmas? :thinking: 
Also, can you add a definition in `proof-libs/fstar/rust_primitives/Rust_primitives.Integers.fst`? (a actual proof would be cool, but if that's taking too much time, put at least an `let ... = admit ()`)

2024-10-16 08:36 UTC, mamonet commented
Definition is already in `proof-libs/fstar/rust_primitives/Rust_primitives.Integers.fst`,  some signatures were dropped while refactoring that module. I will check why it has no proof and see if it's easy to reason that lemma

2024-10-16 08:43 UTC, W95Psp commented
Ahh! Sorry I misunderstood! Sounds good to me!

2024-10-16 08:43 UTC, W95Psp approved these changes

2024-10-25 08:53 UTC, karthikbhargavan approved these changes

2024-11-28 12:51 UTC, franziskuskiefer commented
@karthikbhargavan double check if this got merged already elsewhere.

2024-11-28 13:37 UTC, merged