HaxLib Interface Macro
hacspec/hax pull request #1065
Opened 2024-10-29 11:28 UTC by cmester0

Add interface macro to replace body of hax functions with todo!()

2024-10-29 11:29 UTC, cmester0 commented
I have been using this macro in the annotated-core. I would expect `-i` flag to do this functionality, however it seems not to work for removing just the body with `+:`.

2024-10-31 12:24 UTC, W95Psp commented
We just chatted about this with @cmester0, let's add a proc-macro crates for macro helpers in the annotated lib core.

2024-10-31 12:55 UTC, W95Psp requested changes
As explained in my previous comment, let's add a proc-macro crates for macro helpers in the annotated lib core, and move this there. That makes more sense, and we will be able to name it "backend_primitive" or something like that, which makes sense in the context of the annotated core.

2024-11-08 20:11 UTC, cmester0 commented on hax-lib-macros/src/lib.rs
> +            impl #generics ::core::ops::Deref for #ident <#generics_args> {
This is still relevant

2024-11-08 20:11 UTC, closed without merging