feat(engine/fstar): `let`s instead of typing lambdas
hacspec/hax pull request #333
Opened 2023-11-09 13:40 UTC by W95Psp

We used to have closure like `|x: T, y: U| body` extract to `fun (x:
T) (y: U) -> body` in the F* backend.

When such a typed lambda is consumed by a higer-order function, we sometimes face issues with unification in F*.

This commit introduce a trick that allows for better unification in F*: we now generate a let binding per input in lambdas. For example, `|x: T, y: U| body` now extracts to:
```fstar
fun x y ->
    let x: T = x in
    let y: T = y in
    body
```

2023-11-09 16:16 UTC, franziskuskiefer requested changes
looks like CI is failing
cancelling the review request for now

2023-11-10 10:04 UTC, franziskuskiefer commented
@W95Psp the chacha patch doesn't apply cleanly anymore. You have to update that.

2023-11-10 10:07 UTC, W95Psp commented
Yeah, you're right :( gonna do that.

2023-11-10 12:44 UTC, franziskuskiefer approved these changes
:shipit:

2023-11-10 13:16 UTC, merged