fix(engine/dune): disable js build by default
hacspec/hax pull request #506
Opened 2024-02-13 08:56 UTC by W95Psp

2024-02-19 14:07 UTC, franziskuskiefer requested changes

2024-02-19 14:07 UTC, franziskuskiefer commented on engine/bin/dune
> +; (include dune-js)
Please add a CI job that still tests this. Otherwise it will rot.

2024-05-07 13:26 UTC, franziskuskiefer approved these changes

2024-05-07 14:07 UTC, merged

2024-05-13 06:44 UTC, franziskuskiefer commented
@W95Psp Looks like js build is failing https://github.com/hacspec/hax/actions/runs/9058340703/job/24883799618

2024-05-13 07:03 UTC, W95Psp commented
Oh, I know why... pushing a fix soon

Thanks for noticing!