feat: include flag: allow for dropping bodies
hacspec/hax pull request #612
Opened 2024-04-18 12:28 UTC by W95Psp

This PR adds the `+:` modifier to inclusion clauses. `-i '... +:some::glob::pattern'` will extract signature-only for the items matched by `some::glob::pattern`.

2024-04-21 15:07 UTC, franziskuskiefer requested changes
What exactly is the difference between `+:` and the existing `+~` and `+!`?

Also, this doesn't seem to do the right thing. We need more tests here.
Running this on the sha3 crate on the libcrux dev branch I'm getting and `.fst` as well and the following error
```
error[HAX0008]: (reject_RawOrMutPointer) ExplicitRejection { reason: "a node of kind [Raw_pointer] have been found in the AST" }
  --> libcrux-sha3/src/x4/internal.rs:27:1
```

2024-04-22 06:13 UTC, W95Psp commented
The `-i` clause selects items based on patterns. A pattern selects a number of items.
Patterns are processed from then left to the right, and a prefix modifier says what to do with the selected items.  
 - `+`: include selected items and all their dependencies (transitively);
 - `+~`: include selected items and direct dependencies (no transitivity);
 - `+!`: include selected items without its dependencies;
 - `+:`: include only the type signature of the selected items (dropping bodies).

Concerning the `sha3` crate, that's expected: `internal.rs` contains type definitions that contain unsupported features (raw pointers). A type definition cannot be extracted if any of its variants or fields contains unsupported code, we should just exclude that `internal.rs` file, or, at least, the faulty definition.

2024-04-22 09:07 UTC, franziskuskiefer commented on cli/options/src/lib.rs
> +
```suggestion
    ///
```

2024-04-22 09:07 UTC, franziskuskiefer commented on cli/options/src/lib.rs
> +
```suggestion
    ///
```

2024-04-22 10:48 UTC, franziskuskiefer approved these changes
Thanks, looks like this fixes things.

Let's file follow-ups for all the identified issues.

2024-04-22 10:48 UTC, franziskuskiefer commented on cli/options/src/lib.rs
> +
I'm not sure I understand. You get the line breaks in the help text when you add an empty comment line. And I don't think it makes it harder to read here.
Anyway, not a huge deal. It just looks a little weird here.

2024-04-22 10:54 UTC, W95Psp commented
:+1: filed #617 and #618

2024-04-22 11:40 UTC, merged